pipeline {
    agent { node { label 'AGENT-1' } }
    options {
        ansiColor('xterm')
    }
    stages {
        stage('Init') {
            steps {
                 sh '''
                    cd roboshop-infra-standard/01-vpc
                    ls -ltr
                    pwd
                    terraform init
                 '''
            }
        }
        stage('Plan') {
            steps {
                 sh '''
                    cd roboshop-infra-standard/01-vpc
                    ls -ltr
                    pwd
                    terraform plan
                 '''
            }
        }
        stage('Approve') {
            steps{
                input "Shall I apply?"
            }
        }

          stage('Apply') {
            steps {
                 sh '''
                    cd roboshop-infra-standard/01-vpc
                    ls -ltr
                    pwd
                    terraform apply -auto-approve
                 '''
            }
        }
       
    }
    post { 
        always { 
            echo 'I will always whether job is sucess or not!'
        }
        success{
            echo 'I will run only when the job is success'
        }
        failure{
            echo 'I will run only when the job is failure'
        }
    }
}