pipeline {
    agent { node { label 'AGENT-1' } }
    stages {
        stage('Init') {
            steps {
                 sh '''
                    cd /roboshop-infra-standard
                    ls -ltr
                    pwd
                    terraform init
                 '''
            }
        }
        stage('Plan') {
            steps {
                 sh '''
                    cd /roboshop-infra-standard
                    ls -ltr
                    pwd
                    terraform plan
                 '''
            }
        }
       
    }
    post { 
        always { 
            echo 'I will always whether job is sucess or not!'
        }
        success{
            echo 'I will run only when the job is success'
        }
        failure{
            echo 'I will run only when the job is failure'
        }
    }
}